version: '3.5'

services:

  app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/home/app'
      - '/home/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    network_mode: "host"

